### ISSUE TITLE
Runpod 에서 "TypeError: 'Progress' object is not subscriptable"라고 나옵니다.

### ISSUE THREAD

**Issue by gagongjaryo** [vEduardovich/dodari#1]
안녕하세요! 
사실 저는 runpod라는 곳에서 이걸 사용해 볼까 생각했는데 잘 되지 않아서 문의를 남겨봅니다.
cu-118인 템플릿을 골라서 사용을 했는데 아래와 같은 오류를 뱉어내더라구요.
(RunPod Pytorch 2.1
runpod/pytorch
:2.1.0-py3.10-cuda11.8.0-devel-ubuntu22.04)

코랩에서 사용해보고 싶었는데, 여기는 무료티어에서는 허용하지 않는 코드를 쓴다면서 차단하더라구요.
코랩에서 돌아갈 수 있다면 ipynb 파일을 만들어 배포해볼까 라는 생각도 잠깐 했었습니다만 그건 안될 것 같네요.

구글 검색도 해보고 하는데, gradio나 runpod에서의 버그일수도 있겠단 생각도 들고 하네요. 

조금 빠르게 Runpod에서 쓸수 있을까 생각했었는데 그냥 컴퓨터에 설치해서 잘 쓰도록 하겠습니다.
그래도 오류의 내용을 남기는게 도움 되실것 같아서 아래 문구를 남겨봅니다.

영-한 번역 두번시도 하고, 한영 한번시도했었습니다.
이 오류가 뜰떄 영한번역 모델은 설치되어 있었습니다.

-- 오류 내용(?) --

AI 번역기 도다리를 시작합니다.
잠시만 기다려주세요..
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1191, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 666, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/workspace/dodari/dodari.py", line 70, in translateFn
    name, ext = os.path.splitext(file['orig_name'])
TypeError: 'Progress' object is not subscriptable
Traceback (most recent call last):
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1191, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 666, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/workspace/dodari/dodari.py", line 70, in translateFn
    name, ext = os.path.splitext(file['orig_name'])
TypeError: 'Progress' object is not subscriptable
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 556/556 [00:00<00:00, 1.34MB/s]
sentencepiece.bpe.model: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.85M/4.85M [00:00<00:00, 20.7MB/s]
tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17.3M/17.3M [00:00<00:00, 28.5MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.55k/3.55k [00:00<00:00, 10.0MB/s]
config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 921/921 [00:00<00:00, 2.18MB/s]
model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.47G/2.47G [00:54<00:00, 45.2MB/s]
generation_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 184/184 [00:00<00:00, 953kB/s]
Traceback (most recent call last):
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1191, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 666, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/workspace/dodari/dodari.py", line 70, in translateFn
    name, ext = os.path.splitext(file['orig_name'])
TypeError: 'Progress' object is not subscriptable

**Comment by vEduardovich** [comment]
맞습니다. 저도 최근 이 문제에 대해 알아보고 있습니다.
Gradio의 Progress 메서드가 일부 다른 패키지와 꼬이는 부분이 있는것 같습니다.
tqdm과 vllm에서 사용하는 내부 모듈들 하나와 엮인거 같은데 발생 상황 자체가 흔하지 않아 아직은 파악중입니다.

코랩에서 그런 문제가 있는줄 몰랐습니다. 나중에 코랩버전도 고려해보겠습니다.
이렇게 피드백을 남겨주셔서 정말 감사합니다.

**Comment by vEduardovich** [comment]
> 안녕하세요! 사실 저는 runpod라는 곳에서 이걸 사용해 볼까 생각했는데 잘 되지 않아서 문의를 남겨봅니다. cu-118인 템플릿을 골라서 사용을 했는데 아래와 같은 오류를 뱉어내더라구요. (RunPod Pytorch 2.1 runpod/pytorch :2.1.0-py3.10-cuda11.8.0-devel-ubuntu22.04)
> 
> 코랩에서 사용해보고 싶었는데, 여기는 무료티어에서는 허용하지 않는 코드를 쓴다면서 차단하더라구요. 코랩에서 돌아갈 수 있다면 ipynb 파일을 만들어 배포해볼까 라는 생각도 잠깐 했었습니다만 그건 안될 것 같네요.
> 
> 구글 검색도 해보고 하는데, gradio나 runpod에서의 버그일수도 있겠단 생각도 들고 하네요.
> 
> 조금 빠르게 Runpod에서 쓸수 있을까 생각했었는데 그냥 컴퓨터에 설치해서 잘 쓰도록 하겠습니다. 그래도 오류의 내용을 남기는게 도움 되실것 같아서 아래 문구를 남겨봅니다.
> 
> 영-한 번역 두번시도 하고, 한영 한번시도했었습니다. 이 오류가 뜰떄 영한번역 모델은 설치되어 있었습니다.
> 
> -- 오류 내용(?) --
> 
> AI 번역기 도다리를 시작합니다. 잠시만 기다려주세요.. Running on local URL: http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`. Traceback (most recent call last): File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction output = await route_utils.call_process_api( File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api output = await app.get_blocks().process_api( File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api result = await self.call_function( File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1191, in call_function prediction = await utils.async_iteration(iterator) File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration return await iterator.**anext**() File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 512, in **anext** return await anyio.to_thread.run_sync( File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync return await get_async_backend().run_sync_in_worker_thread( File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread return await future File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run result = context.run(func, *args) File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async return next(iterator) File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 666, in gen_wrapper yield from f(*args, **kwargs) File "/workspace/dodari/dodari.py", line 70, in translateFn name, ext = os.path.splitext(file['orig_name']) TypeError: 'Progress' object is not subscriptable Traceback (most recent call last): File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction output = await route_utils.call_process_api( File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api output = await app.get_blocks().process_api( File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api result = await self.call_function( File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1191, in call_function prediction = await utils.async_iteration(iterator) File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration return await iterator.**anext**() File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 512, in **anext** return await anyio.to_thread.run_sync( File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync return await get_async_backend().run_sync_in_worker_thread( File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread return await future File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run result = context.run(func, *args) File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async return next(iterator) File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 666, in gen_wrapper yield from f(*args, **kwargs) File "/workspace/dodari/dodari.py", line 70, in translateFn name, ext = os.path.splitext(file['orig_name']) TypeError: 'Progress' object is not subscriptable tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 556/556 [00:00<00:00, 1.34MB/s] sentencepiece.bpe.model: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.85M/4.85M [00:00<00:00, 20.7MB/s] tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17.3M/17.3M [00:00<00:00, 28.5MB/s] special_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.55k/3.55k [00:00<00:00, 10.0MB/s] config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 921/921 [00:00<00:00, 2.18MB/s] model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.47G/2.47G [00:54<00:00, 45.2MB/s] generation_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 184/184 [00:00<00:00, 953kB/s] Traceback (most recent call last): File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction output = await route_utils.call_process_api( File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api output = await app.get_blocks().process_api( File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api result = await self.call_function( File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1191, in call_function prediction = await utils.async_iteration(iterator) File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration return await iterator.**anext**() File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 512, in **anext** return await anyio.to_thread.run_sync( File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync return await get_async_backend().run_sync_in_worker_thread( File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread return await future File "/workspace/dodari/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run result = context.run(func, *args) File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async return next(iterator) File "/workspace/dodari/venv/lib/python3.10/site-packages/gradio/utils.py", line 666, in gen_wrapper yield from f(*args, **kwargs) File "/workspace/dodari/dodari.py", line 70, in translateFn name, ext = os.path.splitext(file['orig_name']) TypeError: 'Progress' object is not subscriptable

맞습니다. 저도 vllm을 적용하며 최근 이 상황을 맞닥뜨렸습니다.
내부적으로 gradio의 progress와 tqdm의 progress 혹은 vllm의 progress 모듈에 간섭이 있는 것 같습니다.
발생 상황이 흔치 않아 해결에 약간 시간이 필요할 것 같습니다.

코랩에 그런 문제가 있는 줄은 몰랐네요. 여유가 되면 코랩 버전도 만들어 보도록 하겠습니다.
이렇게 피드백 주셔서 정말 감사합니다.

**Comment by gagongjaryo** [comment]
https://github.com/vEduardovich/dodari_nllb

nllb 버전사용해봤는데 여기서는 오류없이 잘 작동합니다!! 일단 두번째로 큰 모델까지 작동확인했습니다.
압도적으로 감사합니다!!!! 

참고로 세번째 모델은... 안되서(허깅페이스에 없는 모델이라)
https://huggingface.co/facebook/nllb-200-3.3B/tree/main
요걸로 갈아끼우고 써보고있습니다.

**Comment by goINTo425** [comment]
저도 동일하게 TypeError: 'Progress' object is not subscriptable 라는 에러로 번역이 안되네요. 윈도우11 사용중입니다.

**Comment by gagongjaryo** [comment]
[goINTo425](https://github.com/goINTo425)님


일단 저는 
https://github.com/vEduardovich/dodari_nllb 요걸 사용중입니다.
저는 이건 잘 작동하네요. 이거 써보세요.


참고로 설치방법이 

git clone https://github.com/vEduardovich/dodari_nllb.git
cd dodari
아래 방법으로 실행하기
윈도우는 start_windows.bat 실행
맥, 우분투는 sh start_mac.sh 실행

이렇게 적혀있는데 
cd dodari 이부분
cd dodari_nllb로 해야될겁니다.

**Comment by gagongjaryo** [comment]
> 코랩에 그런 문제가 있는 줄은 몰랐네요. 여유가 되면 코랩 버전도 만들어 보도록 하겠습니다. 이렇게 피드백 주셔서 정말 감사합니다.

코랩(콜랩)에서 무료로 그림 뽑는 분들이 계셔서 단속을 안할수가 없었을 겁니다.
특정 기능이나 (터널?? 이라고 하나요 ngrok같은거) 아니면 반복시키는 함수 이런거 좀 단속하는것 같아요.

**Comment by vEduardovich** [comment]
> 저도 동일하게 TypeError: 'Progress' object is not subscriptable 라는 에러로 번역이 안되네요. 윈도우11 사용중입니다.

문제점을 찾았습니다!
최근에 넣은 "번역 중단하기" 기능의 yeild 명령어가 문제를 일으키고 있었습니다.
그래서 리턴값이 꼬이고 있습니다.
일단 번역 중단하기 기능을 최대한 빨리 없애고 업데이트 후 알려드리겠습니다.
피드백 주셔서 감사합니다

**Comment by goINTo425** [comment]
> > 저도 동일하게 TypeError: 'Progress' object is not subscriptable 라는 에러로 번역이 안되네요. 윈도우11 사용중입니다.
> 
> 문제점을 찾았습니다! 최근에 넣은 "번역 중단하기" 기능의 yeild 명령어가 문제를 일으키고 있었습니다. 그래서 리턴값이 꼬이고 있습니다. 일단 번역 중단하기 기능을 최대한 빨리 없애고 업데이트 후 알려드리겠습니다. 피드백 주셔서 감사합니다

감사합니다. 
현재 nllb에 포함되어있는 "nllb-200-distilled-3.3B" 모델이 허깅페이스에서 확인이 안되네요. 해당 문제도 확인해보셔야 할 것 같습니다. 감사합니다.

**Comment by vEduardovich** [comment]
> > > 저도 동일하게 TypeError: 'Progress' object is not subscriptable 라는 에러로 번역이 안되네요. 윈도우11 사용중입니다.
> > 
> > 
> > 문제점을 찾았습니다! 최근에 넣은 "번역 중단하기" 기능의 yeild 명령어가 문제를 일으키고 있었습니다. 그래서 리턴값이 꼬이고 있습니다. 일단 번역 중단하기 기능을 최대한 빨리 없애고 업데이트 후 알려드리겠습니다. 피드백 주셔서 감사합니다
> 
> 감사합니다. 현재 nllb에 포함되어있는 "nllb-200-distilled-3.3B" 모델이 허깅페이스에서 확인이 안되네요. 해당 문제도 확인해보셔야 할 것 같습니다. 감사합니다.

알겠습니다. 바로 확인해보겠습니다.
참고로 위 Progress 문제는 수정후 업데이트 완료했습니다. 제 맥에서 정상적으로 돌아가는 테스트까지 완료하였습니다.
죄송스런 부탁이나, 확인을 요청드려도 될까요?

**Comment by goINTo425** [comment]
> > > > 저도 동일하게 TypeError: 'Progress' object is not subscriptable 라는 에러로 번역이 안되네요. 윈도우11 사용중입니다.
> > > 
> > > 
> > > 문제점을 찾았습니다! 최근에 넣은 "번역 중단하기" 기능의 yeild 명령어가 문제를 일으키고 있었습니다. 그래서 리턴값이 꼬이고 있습니다. 일단 번역 중단하기 기능을 최대한 빨리 없애고 업데이트 후 알려드리겠습니다. 피드백 주셔서 감사합니다
> > 
> > 
> > 감사합니다. 현재 nllb에 포함되어있는 "nllb-200-distilled-3.3B" 모델이 허깅페이스에서 확인이 안되네요. 해당 문제도 확인해보셔야 할 것 같습니다. 감사합니다.
> 
> 알겠습니다. 바로 확인해보겠습니다. 참고로 위 Progress 문제는 수정후 업데이트 완료했습니다. 제 맥에서 정상적으로 돌아가는 테스트까지 완료하였습니다. 죄송스런 부탁이나, 확인을 요청드려도 될까요?

현재 epub 파일을 넣었을때 실행 잘 되고 있습니다. 번역이 끝나면 다시 말씀드릴게요.

**Comment by vEduardovich** [comment]
> > > 저도 동일하게 TypeError: 'Progress' object is not subscriptable 라는 에러로 번역이 안되네요. 윈도우11 사용중입니다.
> > 
> > 
> > 문제점을 찾았습니다! 최근에 넣은 "번역 중단하기" 기능의 yeild 명령어가 문제를 일으키고 있었습니다. 그래서 리턴값이 꼬이고 있습니다. 일단 번역 중단하기 기능을 최대한 빨리 없애고 업데이트 후 알려드리겠습니다. 피드백 주셔서 감사합니다
> 
> 감사합니다. 현재 nllb에 포함되어있는 "nllb-200-distilled-3.3B" 모델이 허깅페이스에서 확인이 안되네요. 해당 문제도 확인해보셔야 할 것 같습니다. 감사합니다.

세상에! 기존 facebook/nllb-200-distilled-3.3B 모델이 삭제되었네요. 양자화되지 않은 facebook/nllb-200-3.3B 모델로 대체하였습니다. 다만 이건 용량이 꽤 크네요. 코드는 모두 수정하고 업데이트까지 완료하였습니다. 저도 해당 모델을 다운받고 있습니다. 품질을 체크해 봐야겠어요.

**Comment by goINTo425** [comment]
> > > > 저도 동일하게 TypeError: 'Progress' object is not subscriptable 라는 에러로 번역이 안되네요. 윈도우11 사용중입니다.
> > > 
> > > 
> > > 문제점을 찾았습니다! 최근에 넣은 "번역 중단하기" 기능의 yeild 명령어가 문제를 일으키고 있었습니다. 그래서 리턴값이 꼬이고 있습니다. 일단 번역 중단하기 기능을 최대한 빨리 없애고 업데이트 후 알려드리겠습니다. 피드백 주셔서 감사합니다
> > 
> > 
> > 감사합니다. 현재 nllb에 포함되어있는 "nllb-200-distilled-3.3B" 모델이 허깅페이스에서 확인이 안되네요. 해당 문제도 확인해보셔야 할 것 같습니다. 감사합니다.
> 
> 세상에! 기존 facebook/nllb-200-distilled-3.3B 모델이 삭제되었네요. 양자화되지 않은 facebook/nllb-200-3.3B 모델로 대체하였습니다. 다만 이건 용량이 꽤 크네요. 코드는 모두 수정하고 업데이트까지 완료하였습니다. 저도 해당 모델을 다운받고 있습니다. 품질을 체크해 봐야겠어요.

네 사실 야놀자 모델 최적화 해주시길 고대하고 있습니다 ㅎㅎ

**Comment by vEduardovich** [comment]
> > 코랩에 그런 문제가 있는 줄은 몰랐네요. 여유가 되면 코랩 버전도 만들어 보도록 하겠습니다. 이렇게 피드백 주셔서 정말 감사합니다.
> 
> 코랩(콜랩)에서 무료로 그림 뽑는 분들이 계셔서 단속을 안할수가 없었을 겁니다. 특정 기능이나 (터널?? 이라고 하나요 ngrok같은거) 아니면 반복시키는 함수 이런거 좀 단속하는것 같아요.

문제가 되는 부분을 확인했고 모두 수정완료했습니다(최근에 추가한 번역중단의 명령어 하나가 문제였습니다)
제가 테스트한 PC들에서는 아무 문제가 없음을 확인하였습니다.
dodari.py 파일 하나만 다운 받으셔서 기존 도다리 폴더에 덮어쓰기 하시고 실행하시면 됩니다.
이렇게 피드백 주신 덕분에 문제를 해결할 수 있었습니다. 감사합니다.
