### ISSUE TITLE
Epub 서식 유지

### ISSUE THREAD

**Issue by goINTo425** [vEduardovich/dodari#2]
해당 프로그램을 사용했을때 대부분의 서식을 없애버리네요.
따라서 epub 파일을 열었을때 이미지들이 보이지 않습니다.
반면 해당 파일 내부에는 이미지들이 여전히 남아있어서 용량을 차지하네요.
해당 서식들을 유지할 수 있는 옵션이 있으면 좋겠습니다.

**Comment by vEduardovich** [comment]
> 해당 프로그램을 사용했을때 대부분의 서식을 없애버리네요. 따라서 epub 파일을 열었을때 이미지들이 보이지 않습니다. 반면 해당 파일 내부에는 이미지들이 여전히 남아있어서 용량을 차지하네요. 해당 서식들을 유지할 수 있는 옵션이 있으면 좋겠습니다.

의견 주셔서 감사합니다.
해당건은 아마도 원본 epub파일이 표준규격에 맞지 않게 제작되어 발생했을 확률이 높습니다.
여러 테스트 결과 5년 이상 오래전에 만들어진 epub의 경우 간혹 이렇게 편의대로 제작된 것을 발견했습니다.

이럴 경우 번역을 위해 텍스트를 뽑아내는 과정에서 이미지 파일들은 소실될수가 있습니다.
정해진 규격을 벗어나 epub제작자가 자신의 임의대로 만든 파일에서 서식을 유지하며 번역하는 것에는 여러 어려움이 따라옵니다.
도다리 개발을 진행하며 다른 여러 epub 라이브러리들을 분석했는데 다른 것들도 마찬가지였습니다. (오히려 도다리보다 떨어졌지요)

최근의 다른 epub 파일들을 번역해보시면 아마 잘 될 것입니다.
말씀 주셔서 감사합니다.

**Comment by vEduardovich** [comment]
> 해당 프로그램을 사용했을때 대부분의 서식을 없애버리네요. 따라서 epub 파일을 열었을때 이미지들이 보이지 않습니다. 반면 해당 파일 내부에는 이미지들이 여전히 남아있어서 용량을 차지하네요. 해당 서식들을 유지할 수 있는 옵션이 있으면 좋겠습니다.

규격을 준수하지 않은 epub의 서식 - 특히 **이미지** -등을 최대한 유지한 채 번역할 수 있도록 업데이트하였습니다.
dodary.py 만 덮어쓰기하시면 바로 적용됩니다.
감사합니다.
