### ISSUE TITLE
[lib] requirements 버전 관련 의견

### ISSUE THREAD

**Issue by Liberatedwinner** [vEduardovich/dodari#4]
안녕하세요,

repo를 살펴보던 중 requirements 목록에 들어가있는 라이브러리의 버전이 
`Gradio==4.14.0`을 제외하면 표기되지 않은 것을 확인했습니다.
개인적인 경험으로는 CUDA 11.x에서 12.x로 이행할 때
Python 라이브러리 및 실행 커널 관련 문제로 골머리를 앓은 적이 많았기에...

부담이 가지 않는 범위에서라도
현재 작업하신 환경의 Python 버전과 라이브러리 버전까지를 표기하는 게
추후 유지보수에 유리할 것이라고 저는 생각하는데
이에 대해 어떻게 생각하시는지 의견을 교환할 수 있으면 좋겠습니다.

읽어주셔서 감사합니다!

**Comment by vEduardovich** [comment]
의견 감사합니다.
gradio은 버전마다 제각각의 버그들이 튀어나와 고정을 할수밖에 없었어요 ㅋㅋ
말씀주신것처럼 배포시에는 버전 고정이 맞는데 제가 게을렀습니다.
다음번 커밋에 적용하기 위해 노력하겠습니다.

**Comment by Liberatedwinner** [comment]
아, 제가 Gradio 버그를 너무 간과했습니다.
게다가 PyTorch 및 그 하위 모듈의 판올림이 은근히 자주 있는 걸 생각하면...
테스트를 충분히 진행하신 다음에 안정화된 환경의 버전을 기재하시는 현재 계획이
훨씬 좋은 방안일 것 같습니다.

염려에서 비롯된 Issue 작성이었다고는 하나... 결과적으론 재촉드린 모양이 되어서 면목이 없습니다.
우선도가 낮은 것이니 Issue를 닫아 다른 분들께서 혼란하시는 걸 막고자 하는데,
닫아도 괜찮을까요?

읽어주셔서 감사합니다!

**Comment by vEduardovich** [comment]
아닙니다. 말씀해주신게 맞습니다.
제가 다음 커밋에 처리할수 있게 노력할께요!

**Comment by Liberatedwinner** [comment]
작은 의견인데도 신경 많이 써주셔서 감사합니다!
