### ISSUE TITLE
#bug epub 파일 번역 결과에 prompt 문장이 포함됩니다.

### ISSUE THREAD

**Issue by partrita** [vEduardovich/dodari#7]
epub파일을 가지고 번역을 해보면 "문장을 추가하지 말고 번역해"라는 prompt가 결과 파일에 포함되어 있는 경우가 있습니다. 모든 파일이 그런건 아니도 특정 조건에서만 나타는 걸 보면 이상한 버그 인것 같습니다.

감사합니다.

**Comment by vEduardovich** [comment]
도다리 고급번역에서 사용하는 yanolja-eeve 모델의 경우에는 그런 경우가 자주 있지만
nhndq모델에서 이런 경우는 처음 보았네요.
현재 llm의 경우 답변을 완전히 컨트롤하는건 조금 어려운 것 같습니다. 예시를 보여주며 아무리 번역만 하라도 요청하고 계속 자신만의 답변을 하는경우가 많더라고요.

고급번역인 yanolja-eeve모델에서도 이 문제를 끝내 해결하지 못했습니다. 그 빈도를 많이 줄이긴했지만 로컬 llm의 환각현상 제거는 아직 어려운일 같습니다

**Comment by partrita** [comment]
> 도다리 고급번역에서 사용하는 yanolja-eeve 모델의 경우에는 그런 경우가 자주 있지만
> 
> nhndq모델에서 이런 경우는 처음 보았네요.
> 
> 현재 llm의 경우 답변을 완전히 컨트롤하는건 조금 어려운 것 같습니다. 예시를 보여주며 아무리 번역만 하라도 요청하고 계속 자신만의 답변을 하는경우가 많더라고요.
> 
> 
> 
> 고급번역인 yanolja-eeve모델에서도 이 문제를 끝내 해결하지 못했습니다. 그 빈도를 많이 줄이긴했지만 로컬 llm의 환각현상 제거는 아직 어려운일 같습니다

환각현상이 이렇게도 나타나는군요. 전혀 몰랐습니다. 좋은 가르침 감사합니다ㅎ
