### ISSUE TITLE
처음 설치하고 실행시 에러가 발생합니다.

### ISSUE THREAD

**Issue by cooverin** [vEduardovich/dodari#8]
설치법대로 파이썬 설치하고 도다리 다운받고 압축 풀고 실행후
파일 다운로드 받고 환경구축후에 바로 에러가 발생합니다.
재실행해도 동일하구요.....꼭 써보고 싶은데 해결책이 없을까요?
<img width="856" alt="화면 캡처 2024-08-05 172502" src="https://github.com/user-attachments/assets/396b1d38-a800-4e1a-a76a-9fc0a88c947f">

**Comment by vEduardovich** [comment]
지금 윈도우 환경에서 다운받고 테스트 중입니다.
잠시만 기다려주세요

**Comment by vEduardovich** [comment]
설치 후 실행 및 번역까지 잘 되고 있어서 재현이 어렵네요.
첨부하신 스샷으로만 보면 torch 모듈이 제대로 설치가 되지 않아서 그런것 같은데요.

![image](https://github.com/user-attachments/assets/a0894e55-e31f-43f7-bd98-1a4b17f6c678)

폴더 중에 venv라는 폴더가 있을 거에요. 여기에 모든 라이브러리들을 설치하는데 여기에 문제가 있는거 같습니다.

1. venv폴더를 먼저 삭제하신 후 
2. 다시 start_windows.bat를 실행하시면 새로 라이브러리들을 설치할 거에요.

그러면 설치 완료후 자동으로 실행이 될겁니다. 이대로 해보시고 다시 문제가 생긴다면 방금처럼 스샷찍어서 보내주세요!

**Comment by vEduardovich** [comment]
설치용량이 아주 크기 때문에 하드에 여유공간이 많아야 해요.
venv 는 10GB가 필요하고
모델에도 5GB 정도가 필요해요.
그러니까 15GB 정도의 저장공간이 있어야만 안정적으로 설치가 가능해요

**Comment by cooverin** [comment]
> 설치 후 실행 및 번역까지 잘 되고 있어서 재현이 어렵네요. 첨부하신 스샷으로만 보면 torch 모듈이 제대로 설치가 되지 않아서 그런것 같은데요.
> 
> ![image](https://private-user-images.githubusercontent.com/20391482/355048746-a0894e55-e31f-43f7-bd98-1a4b17f6c678.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTYwMzksIm5iZiI6MTcyMjg1NTczOSwicGF0aCI6Ii8yMDM5MTQ4Mi8zNTUwNDg3NDYtYTA4OTRlNTUtZTMxZi00M2Y3LWJkOTgtMWE0YjE3ZjZjNjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDExMDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZGQ0M2IwMTYzYmJmZjhkNjM0NWM1OWI1Zjg1ZDVlODlhODljOTg4MjVmNjYzZGJhYmI0MDEyMjFhNDBkMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2kmPkj_1O93BxeeKtnVtMki7Z4wAFLnFe4tpFKH_1Dg)
> 
> 폴더 중에 venv라는 폴더가 있을 거에요. 여기에 모든 라이브러리들을 설치하는데 여기에 문제가 있는거 같습니다.
> 
> 1. venv폴더를 먼저 삭제하신 후
> 2. 다시 start_windows.bat를 실행하시면 새로 라이브러리들을 설치할 거에요.
> 
> 그러면 설치 완료후 자동으로 실행이 될겁니다. 이대로 해보시고 다시 문제가 생긴다면 방금처럼 스샷찍어서 보내주세요!

말씀처럼 venu 폴더 삭제후 재실행해도 동일한 증상입니다.
<img width="867" alt="화면 캡처 2024-08-05 195551" src="https://github.com/user-attachments/assets/e4899b2e-531d-402d-8bd5-18ab75fb775e">

**Comment by cooverin** [comment]
> 설치용량이 아주 크기 때문에 하드에 여유공간이 많아야 해요. venv 는 10GB가 필요하고 모델에도 5GB 정도가 필요해요. 그러니까 15GB 정도의 저장공간이 있어야만 안정적으로 설치가 가능해요

여유공간은 300GB 정도 있는데 아무래도 다운로드과정에 문제가 있는듯 합니다.
전체 폴더 용량이 5.4GB 정도밖에 안되네요.
<img width="299" alt="화면 캡처 2024-08-05 200057" src="https://github.com/user-attachments/assets/a5201c4e-9828-432a-9efe-b13f9faf6bee">
<img width="296" alt="화면 캡처 2024-08-05 200131" src="https://github.com/user-attachments/assets/c52433c2-c2f9-4f43-bcaf-2e1426d3c961">

**Comment by vEduardovich** [comment]
운동을 다녀와서 확인이 좀 늦었습니다. 지금 다시 확인중입니다.

**Comment by vEduardovich** [comment]
맞습니다. venv에서 제대로 설치를 못하고 있는 것 같습니다. 아래의 방법을 시도해 보실래요?

https://www.microsoft.com/ko-kr/download/details.aspx?id=48145&lt
1. 위 링크를 통해 마이크로 소프트의 C++ 라이브러리를 다운로드 후 설치하세요.
2. venv 폴더를 다시 지우고 start_windows.bat 을 실행시켜 주세요.

제가 가진 랩탑과 데스크탑 모두에서 재현이 되지않아 - 아마도 제 pc에는 개발자 모듈이 이미 설치되어 있어서 그런것 같습니다 - 직접 확인은 못했지만 https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969/3 이곳에 유사한 문제 보고와 해결방안이 나와있어 공유드립니다.

먼저 시도해보시고
만약 그럼에도 안된다면 제 venv폴더를 아예 압축해서 보내드리겠습니다. 이것도 버전문제로 안될수 있긴하지만 그때는 또 다른 방법을 찾아보겠습니다.

**Comment by cooverin** [comment]
감사합니다~ 보내주신 두번째 링크의 내용중에서 해결책을 찾았습니다.
따로 libomp140.x86_64.dll 파일을 구해서 c:\\Windows\\system32
 폴더 안에 집어넣으니 정상적으로 실행이 되었습니다.
다시한번 감사드립니다.

**Comment by jeepwoo** [comment]
저도 같은 상황이 발생해서 libomp 140.x86_64.dll을 넣긴했지만 같은 상황이 발생했고,
venv 폴더 용량도 5.30GB 입니다..

**Comment by dskam73** [comment]
C++  redistribution이랑 도다리를 재설치했는데도 계속 에러가 뜨네요. ㅜㅠ
![화면 캡처 2024-10-03 090302](https://github.com/user-attachments/assets/14ec16c0-2d3b-4e3b-8b63-bfdc38173fdb)
